const users = [
  // "straightlynegadgets",
  'phonehubb',
  // "laptoprealm",
  // "phonesforallng",
  // "halostore7",
  // "osdevicesofficial",
  // "olusesi_technologies",
  // "korrectgadgets",
  // "ezzylinkgadgets",
  // "dabz_global",
  // "andrewtechgadgets",
  // "phoneworldnigeria",
  // "doubledphones",
  // "uk_laptop_wenecomputers",
  // "ebuscotechnologies",
  // "zonagadgetstore",
  // "kayzzed",
  // "jollofgadgets",
  // "wow_ng",
  // "reliable_phones",
  // "alrightgadgets",
  // "shoppingspree_co",
  // "korrectgadget",
  // "shopinverse",
  // "adereal_gadgets",
  // "bodmantech",
  // "bigtechdevices",
  // "desweetphones",
  // "ipower_link",
  // "phonesvendor",
  // "greenglobe_gadgets",
  // "canoonstore",
  // "laptopwarehouseonline",
  // "techsourcesng",
  // "gadgetfreakzng",
  // "obiwezy",
  // "myvibeapparel",
  // "surpranoclothing",
  // "kaziloba",
  // "yamba_inspired",
  // "fashion_fastline",
  // "shoepify",
  // "fashion_havana_ke",
  // "hiiii_style",
  // "atadorahfashions",
  // "zanehousekenya",
  // "backyardshoez",
  // "malisafi_yard",
  // "joannakcosmetics",
  // "koreankosmeticske",
  // "beautyclick254",
  // "phoinahaircollection",
  // "makeupcloudke"
];

module.exports = {
  users,
};
